## Лабораторная работа 2.

Орешко Алёна Владимировна. 06.03.2025

## Задание 1.

Встроенные типы объектов:

*1)Числа:*
- int-(неизменяемый)-> 0;1;-1
- float-(неизменяемый) -> 5.0; 7.5
- complex-(неизменяемый) -> 1-j; 4+5j
- bool-(неизменяемый) -> true, false
  
*2)Колекции*
- Последовательности
  1. str(строки)-(неизменяемый)(упорядоченная) -> "Hi", 'How are you?'
  2. list(списки)-(изменяемый)(упорядоченная) -> [1, 2, 3, 4, 5], ['a', 'b']
  3. tuple(кортежи)-(неизменяемый)(упорядоченная) -> (1, 2, 3, 4, 5), ('a', 'b')
- Отображения 
  1. dict(словари)-(изменяемый)(неупорядоченная) -> {'name': 'Alyona'}
- Мн-ва
  1. set-(изменяемый)(неупорядоченная) -> {1, 2, 3}
  2. frozenset-(неизменяемый)(неупорядоченная) -> frozenset([1, 2, 3])

## Задание 2. (2.1-2.2)

**2.1 Понятие объекта. Атрибуты.
Методы. Встроенные типы объектов**

  **Объект** в Python — это базовая сущность для представления данных.
  К объектам в Python относятся: данные встроенных типов, встроенные и
пользовательские функции, файлы, модули, встроенные и пользовательские классы,
экземпляры классов и т.д.
  Внутренне объекты представляют собой области выделенной памяти с достаточным
пространством для хранения информации об объекте.
  **Атрибут** — это имя переменной или имя функции, которое связано с объектом и используется
для получения информации об объекте и совершения действий над этим объектом.
  Атрибуты объектов могут быть именами переменных или именами функций. Если
атрибут объекта является именем функции, то он называется **методом**.

**2.2 Встроенные типы объектов, представляющих числа**

**Decimal** для более точных вычислений с плавающей точкой.

In [41]:
from decimal import Decimal
from decimal import getcontext
getcontext().prec = 10
num1 = Decimal('3.6749')
num2 = Decimal('2.783402')
summa1 = num1 + num2
print(summa1) 

6.458302


**Franction** для работы с дробями.

In [44]:
from fractions import Fraction
frac1 = Fraction(1, 2)  # 1/2
frac2 = Fraction(2, 5)  # 2/5
summa2 = frac1 + frac2
print(summa2)

9/10


**2.3 Встроенные типы последовательностей: str, list, tuple**

Нарезание и конкатенация:

In [421]:
S = 'spam'
S = S[:1] + 'l' + S[2:] 
print(S)

slam


Индексации и конкатенация:
В Rython нельзя выполнять присваивание по индексу, а также, как было описано раннее, строки изменять нельзя.

Примеры для списка и кортежа:

In [64]:
lst = [1, 2, 3, 4] # Список
tpl = (1, 2, 3, 4) # Кортеж

Присваивание по индексу:

In [59]:
lst = [1, 2, 3, 4]
lst[2] = 8 
print(lst)

[1, 2, 8, 4]


**2.4 Встроенный тип отображения: dict**

Структура данных, предоставляющая п.и:

In [71]:
personal_info = {
    'name': ('Алёна', 'Орешко', 'Владимировна'),
    'age': 18,
    'workplace': '-',
    'address': 'г.Бобруйск',
    'email': 'm293866345@gmail.com',
    'phone': '+375(29)3866345'
}

print(personal_info['name'])
print(personal_info['age'])

('Алёна', 'Орешко', 'Владимировна')
18


Более удобный способ хранения информации - словарь

**2.5 Встроенный тип множества: set**

In [79]:
s = "aaa bbac cffdddgffaae"
unique_chars = set()#мн-во для уникальных
result = []
#проход по каждому символу с проверкой встречался ли такой символ уже. если нет, добавляем к мн-ву
for char in s:
    if char not in unique_chars:
        unique_chars.add(char)
        result.append(char)
result_str = ''.join(result)#преобразовали обратно в строку
print(result_str)

a bcfdge


**2.6 Встроенный булевый тип**

Значения True/False. Для логических операций и условных выражений.

**2.7 Изменяемые и неизменяемые встроенные типы объектов**

Встроенные типы делятся на изменяемые и неизменяемые.

Изменяемые: словари, списки, мн-ва.
Неизменяемые: числа, кортежи, строки.

Неизменяемые после создания изменять нельзя, в изменяемые можно вносить изменения.

**2.8 Интерфейс объекта: операции и методы**

$\textcolor{orange}{\text{1)Приведите примеры вызова методов count и index для всех
возможных типов объектов.}}$

In [89]:
# Пример для строки
str = "aabbddaf"
print(str.count('a'))  # Количество букв'a'
print(str.index('f'))  # Индекс указанного символа

3
7


In [134]:
# Пример для списка
str1 = [3, 2, 6, 1, 7, 5, 4, 1]
print(str1.count(1)) 
print(str1.index(6))  

2
2


Count возвращает кол-во. Index возвращает индекс

$\textcolor{orange}{\text{
2)Приведите пример выражения, в котором для заданной строки
последовательно применены три различных строковых метода.}}$

.swapcase()                     - Инвертирует регистр символов (большие → маленькие, маленькие → большие).

strip()                         - Удаляет пробелы в начале и конце строки.

.replace("символ1", "символ2")  - Заменяет символ1 на символ2

In [136]:
str2 = " aaAb bCccCcd dDtt "
result = str2.strip().swapcase().replace("C", "1")
print(result)

AAaB Bc11c1D DdTT


$\textcolor{orange}{\text{3)Приведите примеры добавления элемента в список с использованием
трех различных списковых методов.}}$

In [139]:
str3 = [1, 2, 3, 4]
str3.append(5) #к концу списка добавит 5
str3.insert(4, 0)#куда добавить, какой эл-т
str3.extend([8, 9])#добавляет перечисленные эл-ты в конец данного списка(.append() добавляет то, что в скобках, как один целый эл-т)
print(str3)

[1, 2, 3, 4, 0, 5, 8, 9]


$\textcolor{orange}{\text{4)Приведите пример сортировки списка с использованием метода sort и
заданного аргумента key. Прокомментируйте результат вычисления.}}$

Сортировка по длине строки:

In [146]:
str4 = ['aaaabb', 'bbbdddgggr', 'gdgjjggsx']
str4.sort(key=len) 
print(str4)

['aaaabb', 'gdgjjggsx', 'bbbdddgggr']


Сортировка по модулю:

In [148]:
str5 = [-4, 5 -2, 7, -3, 1, 0]
str5.sort(key=abs)
print(str5)

[0, 1, 3, -3, -4, 7]


Сортировка по последней букве слова:

In [153]:
str5 = ["hgdswje", "kmkffta", "bggtyjubf", "dfdfgha"]
str5.sort(key=lambda x: x[-1])
print(str5) 

['kmkffta', 'dfdfgha', 'hgdswje', 'bggtyjubf']


Аргумент key позволяет управлять критериями сортировки и не изменяет исходные данные.

$\textcolor{orange}{\text{5)Создайте словарь из 100 элементов с одинаковыми значениями.}}$

In [214]:
slovar = {i: 'value' for i in range(100)}
print("Словарь:", slovar)

Словарь: {0: 'value', 1: 'value', 2: 'value', 3: 'value', 4: 'value', 5: 'value', 6: 'value', 7: 'value', 8: 'value', 9: 'value', 10: 'value', 11: 'value', 12: 'value', 13: 'value', 14: 'value', 15: 'value', 16: 'value', 17: 'value', 18: 'value', 19: 'value', 20: 'value', 21: 'value', 22: 'value', 23: 'value', 24: 'value', 25: 'value', 26: 'value', 27: 'value', 28: 'value', 29: 'value', 30: 'value', 31: 'value', 32: 'value', 33: 'value', 34: 'value', 35: 'value', 36: 'value', 37: 'value', 38: 'value', 39: 'value', 40: 'value', 41: 'value', 42: 'value', 43: 'value', 44: 'value', 45: 'value', 46: 'value', 47: 'value', 48: 'value', 49: 'value', 50: 'value', 51: 'value', 52: 'value', 53: 'value', 54: 'value', 55: 'value', 56: 'value', 57: 'value', 58: 'value', 59: 'value', 60: 'value', 61: 'value', 62: 'value', 63: 'value', 64: 'value', 65: 'value', 66: 'value', 67: 'value', 68: 'value', 69: 'value', 70: 'value', 71: 'value', 72: 'value', 73: 'value', 74: 'value', 75: 'value', 76: 'value',

**2.9 Переменная**

$\textcolor{green}{\text{1)Приведите примеры создания циклического объекта для различных
встроенных типов.}}$

Добавляем список в самого себя

In [223]:
lst = []
lst.append(lst)  
print(lst)       

[[...]]


Ключ "self" ссылается на сам словарь

In [228]:
d = {}
d["self"] = d    
print(d)        

{'self': {...}}


$\textcolor{green}{\text{2)Создайте объект, на который ссылаются четыре переменные. Как можно
узнать количество ссылок для заданного объекта?}}$

4 переменные ссылаются на один и тот же список

In [242]:
import sys
a = b = c = d = [1, 2, 3]
print (a)
print (b)
print (c)
print (d)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


In [253]:
kolssilok = sys.getrefcount(a) - 1
print(kolssilok)

4


In [ ]:
sys.getrefcount(a) определяет кол-во ссылок. Но список сам по себе является ссылкой, соответственно отнимем 1.

$\textcolor{green}{\text{3)Приведите три различных способа копирования списка.}}$

1) Метод Copy:

In [256]:
a1 = [1, 2, 3]
a2 = a1.copy()
print(a2)  

[1, 2, 3]


2) Срез [:]

In [260]:
a3 = [1, 2, 3]
a4 = a3[:]
print(a4)

[1, 2, 3]


3) list():

In [265]:
a5 = [1, 2, 3]
a6 = list(a5)
print(a6) 

[1, 2, 3]


**2.10 Выражение спискового включения**

$\textcolor{pink}{\text{1)Приведите пример создания множества с использованием синтаксиса
включения с условием.}}$

Мн-во четных чисел в указанном промежутке:

In [271]:
mnoghestvo1 = {x for x in range(21) if x % 2 == 0}
print(mnoghestvo1)

{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20}


Мн-во слов длиннее заданной длинны:

In [273]:
mnoghestvo2 = ["hnjk", "a", "bai", "khklrfi", "dghkt"]
mnoghestvo3 = {word for word in mnoghestvo2 if len(word) > 4}
print(mnoghestvo3) 

{'khklrfi', 'dghkt'}


$\textcolor{pink}{\text{2)Приведите пример создания числовой матрицы размера 7 × 8 на основе
списка с использованием включений, вложенных друг в друга.
Попробуйте создать аналогичную матрицу, используя инструменты
расширения numpy..}}$

In [296]:
matrica1 = [[i*8 + j for j in range(8)] for i in range(7)]
for row in matrica1:
    print(row)

[0, 1, 2, 3, 4, 5, 6, 7]
[8, 9, 10, 11, 12, 13, 14, 15]
[16, 17, 18, 19, 20, 21, 22, 23]
[24, 25, 26, 27, 28, 29, 30, 31]
[32, 33, 34, 35, 36, 37, 38, 39]
[40, 41, 42, 43, 44, 45, 46, 47]
[48, 49, 50, 51, 52, 53, 54, 55]


С помощью numpy:

In [319]:
import numpy as np
np_matrica2 = np.arange(56).reshape(7, 8)
print(np_matrica2)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]


$\textcolor{pink}{\text{3)Приведите пример создания словаря с использованием синтаксиса
включения с двумя уровнями вложенности.}}$

In [314]:
slov = {i: {j: j**2 for j in range(5)} for i in range(6)}
print(slov)

{0: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}, 1: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}, 2: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}, 3: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}, 4: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}, 5: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}}


**2.11 Форматированный вывод строк**

$\textcolor{blue}{\text{1)Приведите пример форматированного вывода с использованием
синтаксиса f’…{variable=:…}’, где variable – заданная
переменная. Получите аналогичный результат с использованием
бинарной операции % и строкового метода format.}}$

1) Синтаксис f-строки:

In [324]:
pi = 3.14159
print(f"{pi = :.2f}")  

pi = 3.14


2) Оператор %:

In [327]:
print("pi = %.2f" % pi) 

pi = 3.14


3) Метод .format():

In [332]:
print("pi = {:.2f}".format(pi)) 

pi = 3.14


$\textcolor{pink}{\text{2)Приведите пример форматированного вывода с использованием
синтаксиса f’…{expression=:…}’, где expression – заданное
выражение. Получите аналогичный результат с использованием
бинарной операции % и строкового метода format.
}}$

1) f-строкa: 

In [347]:
print(f"{(5 + 4) * 2 + 1 =:.2f}") 

(5 + 4) * 2 + 1 =19.00


2) Оператор %:

In [364]:
res = (5 + 4) * 2 + 1
print("res = %.2f" % res)

res = 19.00


3) Метод .format():

In [367]:
res2 = (5 + 4) * 2 + 1
print("res2 = {:.2f}".format(res2))  

res2 = 19.00


**2.12 Файловый объект**

In [ ]:
file = open("example.txt", "w") #открытие файла в режиме записи
file.write("Первая строка\n") #write для записи одной строки
lines = ["Вторая строка\n", "Третья строка\n", "Четвертая строка\n"] #writelines для записи списка строк
file.writelines(lines)
file.close()  #закрываем файл
file = open("example.txt", "r")  #открытие файла в режиме чтения
content = file.read()#read для чтения всего содержимого
print("=== read() ===")
print(content)
file.close()
file = open("example.txt", "r")
first_line = file.readline()#readline для чтения первой строки
print("\n=== readline() ===")
print(first_line, end='')
remaining_lines = file.readlines() #readlines для чтения всех оставшихся строк
print("\n=== readlines() ===")
print(remaining_lines)
file.close()

## 2.3

1) print('\c \xc6')

Ошибка возникает из-за \c, которая не является правильной escape-последовательностью. Python не знает, что с ней делать, поэтому выдает предупреждение.

2) str1[10]

Ошибка IndexError возникает, потому что индекс 10 выходит за пределы длины строки str1. В Python индексы начинаются с 0, и если строка короче 11 символов, этот индекс недоступен.

3) [1] + '1'

Ошибка TypeError возникает, потому что в Python нельзя объединять список и строку напрямую.

4) dict1['two']

Ошибка KeyError возникает, потому что ключ 'two' отсутствует в словаре dict1.

5) t = [1,2], {1:2}, {1,2}; t[0] = 0

Ошибка TypeError возникает, потому что t является кортежем, а кортежи в Python неизменяемы.

6) {1, 'str', (1,)}.add([1])

Ошибка TypeError возникает, потому что нельзя добавлять список [1] в множество.

7) print(dict1.get('one'), dict1.get('three')); dict1['three']

Ошибка KeyError возникает, потому что вы пытаетесь получить значение по ключу 'three', который отсутствует в словаре dict1. Метод .get() возвращает None, если ключ не найден, но доступ к несуществующему ключу с помощью dict1['three'] вызывает ошибку.

8) print(s, s.find('-')); s.index('-')

Ошибка ValueError возникает, потому что метод index() не находит подстроку '-' в строке s.

9) a = 1  # создание переменной; a, d

Ошибка NameError возникает, потому что переменная d не определена.

10) print(abs(-1)); abs = 5; print(abs(-1))

Ошибка TypeError возникает, потому что после присвоения abs = 5, abs больше не ссылается на функцию abs(), а становится целым числом.

## Задание 3

4.4 Последовательность — это упорядоченная коллекция элементов, где каждый элемент имеет определенную позицию (индекс). 
В эту категорию входят списки, кортежи, строки.

Примеры соотственно:

In [408]:
llist = [1, 2, "afjf", True]

In [410]:
ttuple = (10, "kkv", False)

In [412]:
sstr = "Hello, World!"

5.4 Модуль math.  x ** 2; x**0.5; pow(x, 2); pow(x, 0.5); math.sqrt(n) 

In [418]:
x=25
b=pow(x, 2)
c=x**0.5
print (b)
print (c)

625
5.0


6.1 Нет.
A = 'spam'
B = A
B = 'shrubbery'

Изначально даны две переменные. А ссылается на 'spam', В ссылается на А, соответственно тоже на 'spam'. Далее у переменной А больше нет присваиваний, следовательно на выходе она также будет выводить 'spam'. А вот переменная В присваивает себе ново значение, строку 'shrubbery', соответственно утрачивает старое значение. Все переменные ссылаются на что-то, по факту явл ссылками для перехода к значению. 

7.4 Строку нельзя изменять после создания. Но можно создать новую, которую получим путем разрезания старой. 

In [430]:
S = 'spam'
S = S[:1] + 'l' + S[2:] 
print(S)

slam


8.1

In [433]:
sspisok = [0] * 5
print(sspisok)

[0, 0, 0, 0, 0]


In [435]:
ssspisok = [0 for _ in range(5)]
print(ssspisok)

[0, 0, 0, 0, 0]


9.2

In [442]:
kortegh1 = (4, 5, 6)
kortegh2 = (1,) + kortegh1[1:]
kortegh2

(1, 5, 6)